approvedGitRepositories:
  - '**'

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - '@julusian/*'
  - node-hid

supportedArchitectures:
  cpu:
    - x64
    - arm64
    - ia32
  os:
    - current
